services:

  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: courses
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    extends:
      file: common-config.yaml
      service: network-configuration

  course-management-system:
    image: "rupesh1997/course-management-system:1.0.0"
    container_name: course-management-system
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8181:8181"
    environment:
      SPRING_APPLICATION_NAME: "course-management-system"
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/courses?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
    extends:
      file: common-config.yaml
      service: network-configuration

  course-management-system-frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile
      args:
        CONFIGURATION: docker
    container_name: course-management-system-frontend
    depends_on:
      course-management-system:
        condition: service_started
    ports:
      - "8080:8080"
    extends:
      file: common-config.yaml
      service: network-configuration

networks:
  cms-network:
    driver: bridge

volumes:
  mysql-data:

  # docker ps
  # docker images
  # docker system prune -f
  # docker compose -f docker/docker-compose/default/docker-compose.yaml down
  # docker compose -f docker/docker-compose/default/docker-compose.yaml up -d