version: "3.9"

services:
  course-management-system:
    container_name: course-management-system
    image: rupesh1997/course-management-system:1.0.0
    ports:
      - "8181:8181"
    networks:
      - course-management-system-nw


#  course-management-system-frontend:
#    container_name: course-management-system-frontend
#    image: rupesh1997/course-management-system-frontend:1.0.0
#    depends_on:
#      - course-management-system
#    ports:
#      - "8080:8080"
#    networks:
#      - course-management-system-nw


networks:
  course-management-system-nw:
    driver: bridge

# docker compose -f docker/docker-compose.yml up -d