spring:
  config:
    activate:
      on-profile: "staging"

info:
  app:
    name: Course Management System
    description: Handles courses management.
    version: 1.0.0
    owner: Rupesh Dulal
    website: https://www.alfarays.tech
    profile: staging
  build:
    timestamp: "@timestamp@"
  developer:
    name: "Rupesh Dulal"
    email: "rupeshdulal672@gmail.com"
    github: "https://github.com/rupeshdulal"